# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: itool
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
#    - go generate ./...
builds:
  - id: build-darwin-amd64
    binary: itool
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
  - id: build-linux-amd64
    binary: itool
    env:
      - CGO_ENABLED=1
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: tar.gz
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    allow_different_binary_count: true
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

